FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ENV NEXT_PUBLIC_PLAUSIBLE_TOKEN=1BV3x6gK-dyyzh0CkYu7WDk4K9AaQnLY6XawWR_s8ue-qoPNpwWSc1wCM9RBf6UK
ENV NEXT_PUBLIC_IMPERSONATE_SECRET=RTUILM40

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
